#pragma once

#include <memory>

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicAnalyzer
{
	namespace Properties
	{
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Runtime.CompilerServices.CompilerGeneratedAttribute()][System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")] internal sealed partial class Settings: System.Configuration.ApplicationSettingsBase
		class Settings final : public System::Configuration::ApplicationSettingsBase
		{

		private:
			static std::shared_ptr<Settings> defaultInstance;

		public:
			const static std::shared_ptr<Settings> &getDefault();

protected:
			std::shared_ptr<Settings> shared_from_this()
			{
				return std::static_pointer_cast<Settings>(System.Configuration.ApplicationSettingsBase::shared_from_this());
			}
		};
	}
}
