#pragma once

#include <memory>

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicAnalyzer
{
	namespace Properties
	{


		/// <summary>
		///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
		/// </summary>
		// Этот класс создан автоматически классом StronglyTypedResourceBuilder
		// с помощью такого средства, как ResGen или Visual Studio.
		// Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
		// с параметром /str или перестройте свой проект VS.
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")][System.Diagnostics.DebuggerNonUserCodeAttribute()][System.Runtime.CompilerServices.CompilerGeneratedAttribute()] internal class Resources
		class Resources : public std::enable_shared_from_this<Resources>
		{

		private:
			static std::shared_ptr<System::Resources::ResourceManager> resourceMan;

			static std::shared_ptr<System::Globalization::CultureInfo> resourceCulture;

		public:
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")] internal Resources()
			Resources();

			/// <summary>
			///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
			/// </summary>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)] internal static System.Resources.ResourceManager ResourceManager
			const static std::shared_ptr<System::Resources::ResourceManager> &getResourceManager();

			/// <summary>
			///   Перезаписывает свойство CurrentUICulture текущего потока для всех
			///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
			/// </summary>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)] internal static System.Globalization.CultureInfo Culture
			const static std::shared_ptr<System::Globalization::CultureInfo> &getCulture();
			static void setCulture(const std::shared_ptr<System::Globalization::CultureInfo> &value);
		};
	}
}
